<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "finewsletter"
 *
 * Auto generated by Extension Builder 2014-08-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Newsletter',
	'description' => 'Another newsletter extension.',
	'category' => 'plugin',
	'author' => 'Patrick Finkbeiner',
	'author_email' => 'mail@finkbeiner.me',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);